### ISSUE TITLE
cmake ignores -DBUILD_TESTS=OFF

### ISSUE THREAD

**Issue by billpriest** [CD3/libInterpolate#10]
Here is what I did (possible that I need a newer version of Boost or some other issue; I tried various --std=cc++ options to no avail).

git clone https://github.com/CD3/libInterpolate.git
cd libInterpolate
git checkout 2.5
mkdir build2.5
cd build2.5
cmake -DCMAKE_CXX_FLAGS=-std=c++14 -DBUILD_TESTS=OFF ..
make

This worked completed (but it built the tests).
------------------------------------------------------------
cd ..
git checkout 2.6
mkdir build2.6
cd build2.6
cmake -DCMAKE_CXX_FLAGS=-std=c++14 -DBUILD_TESTS=OFF ..
make

Here is the output from cmake
----------------------------------------
-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.32.0") 
-- libInterpolate version: 2.6
-- Found Boost: /usr/local/lib/cmake/Boost-1.77.0/BoostConfig.cmake (found version "1.77.0")  
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Found GSL: /usr/local/include (found version "2.7") 
-- Detected Catch-based Unit Test Sources:
--   CatchTests/1D/AnyInterpolator.cpp
--   CatchTests/1D/Constructors.cpp
--   CatchTests/1D/CubicSplineInterpolatorTests.cpp
--   CatchTests/1D/InterpolatorBaseTests.cpp
--   CatchTests/1D/LinearInterpolatorTests.cpp
--   CatchTests/1D/MonotonicInterpolatorTests.cpp
--   CatchTests/1D/Performance.cpp
--   CatchTests/1D/RuntimePolymorphism.cpp
--   CatchTests/1D/Semantics.cpp
--   CatchTests/2D/AnyInterpolator.cpp
--   CatchTests/2D/BicubicInterpolatorTests.cpp
--   CatchTests/2D/BilinearInterpolatorTests.cpp
--   CatchTests/2D/Constructors.cpp
--   CatchTests/2D/InterpolatorBaseTests.cpp
--   CatchTests/2D/LinearDelaunayTriangleInterpolator.cpp
--   CatchTests/2D/Performance.cpp
--   CatchTests/2D/RuntimePolymorphism.cpp
--   CatchTests/2D/Semantics.cpp
--   CatchTests/2D/ThinPlateSplineInterpolatorTests.cpp
--   CatchTests/2D/TriangleInterpolatorBaseTests.cpp
--   CatchTests/Bugs/MonotonicInterpolatorWithFloat.cpp
--   CatchTests/Devel.cpp
--   CatchTests/Examples.cpp
--   CatchTests/UtilsTests.cpp
--   CatchTests/main.cpp
-- Configuring done
-- Generating done
----------------------------------------
This errored out with lots of STL issues in building the tests.
--------------------------------------------------
/usr/bin/c++ -DHAVE_GSL -DTESTING -I/home/priestwilliaml/libinterp/libInterpolate/testing/include -I/home/priestwilliaml/libinterp/libInterpolate/src -I/home/priestwilliaml/libinterp/libInterpolate/build2.6/include -isystem /usr/local/include/eigen3 -std=c++14 -Wall -Wextra -pedantic -Wno-unknown-pragmas -Wno-unused-parameter -Wno-gnu-zero-variadic-macro-arguments -Werror -std=gnu++11 -o CMakeFiles/libInterpolate_CatchTests.dir/CatchTests/1D/Performance.cpp.o -c /home/priestwilliaml/libinterp/libInterpolate/testing/CatchTests/1D/Performance.cpp
In file included from /usr/local/include/boost/geometry/geometry.hpp:26,
                 from /usr/local/include/boost/geometry.hpp:17,
                 from /home/priestwilliaml/libinterp/libInterpolate/src/libInterpolate/./Interpolators/_2D/DelaunayTriangulationInterpolatorBase.hpp:12,
                 from /home/priestwilliaml/libinterp/libInterpolate/src/libInterpolate/./Interpolators/_2D/LinearDelaunayTriangleInterpolator.hpp:3,
                 from /home/priestwilliaml/libinterp/libInterpolate/src/libInterpolate/Interpolate.hpp:8,
                 from /home/priestwilliaml/libinterp/libInterpolate/testing/CatchTests/1D/Performance.cpp:4:
/usr/local/include/boost/geometry/geometry.hpp:27:1: note: ‘#pragma message: CAUTION: Boost.Geometry in Boost 1.73 deprecates support for C++03 and will require C++14 from Boost 1.75 onwards.’
   27 | BOOST_PRAGMA_MESSAGE("CAUTION: Boost.Geometry in Boost 1.73 deprecates support for C++03 and will require C++14 from Boost 1.75 onwards.")
      | ^~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/geometry/geometry.hpp:28:1: note: ‘#pragma message: CAUTION: Define BOOST_GEOMETRY_DISABLE_DEPRECATED_03_WARNING to suppress this message.’
   28 | BOOST_PRAGMA_MESSAGE("CAUTION: Define BOOST_GEOMETRY_DISABLE_DEPRECATED_03_WARNING to suppress this message.")
      | ^~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/include/boost/geometry/core/tag.hpp:23,
                 from /usr/local/include/boost/geometry/core/ring_type.hpp:28,
                 from /usr/local/include/boost/geometry/core/closure.hpp:23,
                 from /usr/local/include/boost/geometry/geometry.hpp:34,
                 from /usr/local/include/boost/geometry.hpp:17,
                 from /home/priestwilliaml/libinterp/libInterpolate/src/libInterpolate/./Interpolators/_2D/DelaunayTriangulationInterpolatorBase.hpp:12,
                 from /home/priestwilliaml/libinterp/libInterpolate/src/libInterpolate/./Interpolators/_2D/LinearDelaunayTriangleInterpolator.hpp:3,
                 from /home/priestwilliaml/libinterp/libInterpolate/src/libInterpolate/Interpolate.hpp:8,
                 from /home/priestwilliaml/libinterp/libInterpolate/testing/CatchTests/1D/Performance.cpp:4:
/usr/local/include/boost/geometry/util/type_traits_std.hpp:54:25: error: expected template-name before ‘<’ token
   54 |     : std::conditional_t<Trait::value, conjunction<Traits...>, Trait>
      |                         ^
/usr/local/include/boost/geometry/util/type_traits_std.hpp:54:25: error: expected ‘{’ before ‘<’ token
/usr/local/include/boost/geometry/util/type_traits_std.hpp:68:25: error: expected template-name before ‘<’ token
   68 |     : std::conditional_t<Trait::value, Trait, disjunction<Traits...>>
      |                         ^
/usr/local/include/boost/geometry/util/type_traits_std.hpp:68:25: error: expected ‘{’ before ‘<’ token
/usr/local/include/boost/geometry/util/type_traits_std.hpp:95:23: error: ‘remove_cv_t’ in namespace ‘std’ does not name a template type; did you mean ‘remove_cv’?
   95 |     using type = std::remove_cv_t<std::remove_reference_t<T>>;
      |                       ^~~~~~~~~~~
      |                       remove_cv
---------------------------------------

**Comment by CD3** [comment]
Thanks for the issue. That option is part of a template I used to use, and I apparently never set it up correctly. I fixed the `CMakeLists.txt` and tagged it 2.6.1. It is currently on the HEAD of the master branch.

**Comment by billpriest** [comment]
So BUILD_TESTS=OFF worked perfectly.  Building w/ ON worked; however, I saw failures with make test (2.5 fails for me also; I don't remember if I've ever run the tests or not).

Thanks for the quick fix.  Let me know if there is any info I can provide to debug the test failure.  Works w/ my code; so could be just a unit test bug.

make test
Running tests...
Test project /home/priestwilliaml/buildarm/build/libInterpolate/buildx86
    Start 1: libInterpolate_CatchTests
1/1 Test #1: libInterpolate_CatchTests ........***Failed    0.00 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.00 sec

The following tests FAILED:
 1 - libInterpolate_CatchTests (Failed)
Errors while running CTest

________________________________

**Comment by CD3** [comment]
@billpriest Sorry I didn't see this earlier. I will see if I can reproduce this issue.
