### ISSUE TITLE
2D cubic interpolation

### ISSUE THREAD

**Issue by Leersmaekers** [CD3/libInterpolate#11]
Dear,

I wanted to use the 2D cubic interpolation, and came across an issue regarding the output. The input vectors x and y in my example, are formed by the array of doubles [0 1 2 3 4]. When applying the BicubicInterpolator with [xi yi] = [2.5 2.5], I get an aswer of 5.9375, while I expected 6.25. E.g. the BilinearInterpolator provides the correct answer. I added an attachement with the code I used to test the 2D interpolators.
[2D_Example.txt](https://github.com/CD3/libInterpolate/files/8488468/2D_Example.txt)

Kind regards,
Laurent Keersmaekers

**Comment by Leersmaekers** [comment]
I think I may have found the issue. Lines 198 to 204 now are:

fp = (*Z)(i,jp);
      fm = (*Z)(i,jm);
      fy01 = (fp - fm) / yL; // <<<<<<

      fp = (*Z)(i+1,jp);
      fm = (*Z)(i+1,jm);
      fy11 = (fp - fm) / yL; // <<<<<<


And should be replaced by:

fp = (*Z)(i,jp);
      fm = (*Z)(i,jm);
      fy01 = (fp - fm) / dy; // <<<<<<

      fp = (*Z)(i+1,jp);
      fm = (*Z)(i+1,jm);
      fy11 = (fp - fm) / dy; // <<<<<<


Kind regards,
Laurent Keersmaekers

**Comment by CD3** [comment]
Thank you for the issue, the 2D interpolators are not nearly as well tested as 1D.

I will not be able to look at this very soon, but when I have time I will go back through the derivation of the 2D cubic spline method.

In the mean time, would you be able to implement a unit test that fails on this bug so I can implement a fix that gives the desired behavior?

**Comment by Leersmaekers** [comment]
```
#include "pch.h"
#include "CppUnitTest.h"
#include <libInterpolate/Interpolate.hpp>

using namespace Microsoft::VisualStudio::CppUnitTestFramework;

namespace UnitTest1
{
	TEST_CLASS(UnitTest1)
	{
	public:

		TEST_METHOD(TestMethod1)
		{
			std::vector<double> x2, y2, z2;
			double valTest = 2.5;

			for (int i = 0; i < 5; i++)
			{
				for (int j = 0; j < 5; j++)
				{
					x2.push_back((double)i);
					y2.push_back((double)j);
					z2.push_back((double)i * (double)j);
				}
			}

			_2D::BicubicInterpolator<double> interpBiCub;
			interpBiCub.setData(x2, y2, z2);

			double valBiCub = interpBiCub(valTest, valTest);
			double valBiTh = valTest * valTest;

			bool success = false;

			if (fabs(valBiTh - valBiCub) < 1.0e-8)
			{
				success = true;
			}

			Assert::AreEqual(success, true);
		}
	};
}
```

**Comment by Leersmaekers** [comment]
In the above code, I used a tolerance of 1.0e-8. Since the function I used is quadratic w.r.t. to the combination of x and y, the cubic interpolator should be able to stay within this accuracy without any issues. The original interpolator will fail, because the difference between the theoretical value and the interpolated value will exceed 1.0e-8 (by far).

**Comment by CD3** [comment]
Thanks for reporting the issue. I went through the method this weekend and implemented your fix.
