### ISSUE TITLE
Fails to build on OSX: std::iterator is deprecated

### ISSUE THREAD

**Issue by cdutsov** [CD3/libInterpolate#12]
`➜ cmake --build . --target install
[  3%] Building CXX object testing/CMakeFiles/libInterpolate_CatchTests.dir/CatchTests/1D/AnyInterpolator.cpp.o
[  7%] Building CXX object testing/CMakeFiles/libInterpolate_CatchTests.dir/CatchTests/1D/Constructors.cpp.o
[ 11%] Building CXX object testing/CMakeFiles/libInterpolate_CatchTests.dir/CatchTests/1D/CubicSplineInterpolatorTests.cpp.o
[ 15%] Building CXX object testing/CMakeFiles/libInterpolate_CatchTests.dir/CatchTests/1D/InterpolatorBaseTests.cpp.o
[ 19%] Building CXX object testing/CMakeFiles/libInterpolate_CatchTests.dir/CatchTests/1D/LinearInterpolatorTests.cpp.o
[ 23%] Building CXX object testing/CMakeFiles/libInterpolate_CatchTests.dir/CatchTests/1D/MonotonicInterpolatorTests.cpp.o
[ 26%] Building CXX object testing/CMakeFiles/libInterpolate_CatchTests.dir/CatchTests/1D/Performance.cpp.o
[ 30%] Building CXX object testing/CMakeFiles/libInterpolate_CatchTests.dir/CatchTests/1D/RuntimePolymorphism.cpp.o
[ 34%] Building CXX object testing/CMakeFiles/libInterpolate_CatchTests.dir/CatchTests/1D/Semantics.cpp.o
[ 38%] Building CXX object testing/CMakeFiles/libInterpolate_CatchTests.dir/CatchTests/2D/AnyInterpolator.cpp.o
[ 42%] Building CXX object testing/CMakeFiles/libInterpolate_CatchTests.dir/CatchTests/2D/BicubicInterpolatorTests.cpp.o
[ 46%] Building CXX object testing/CMakeFiles/libInterpolate_CatchTests.dir/CatchTests/2D/BilinearInterpolatorTests.cpp.o
[ 50%] Building CXX object testing/CMakeFiles/libInterpolate_CatchTests.dir/CatchTests/2D/Constructors.cpp.o
[ 53%] Building CXX object testing/CMakeFiles/libInterpolate_CatchTests.dir/CatchTests/2D/InterpolatorBaseTests.cpp.o
[ 57%] Building CXX object testing/CMakeFiles/libInterpolate_CatchTests.dir/CatchTests/2D/LinearDelaunayTriangleInterpolator.cpp.o
[ 61%] Building CXX object testing/CMakeFiles/libInterpolate_CatchTests.dir/CatchTests/2D/Performance.cpp.o
[ 65%] Building CXX object testing/CMakeFiles/libInterpolate_CatchTests.dir/CatchTests/2D/RuntimePolymorphism.cpp.o
[ 69%] Building CXX object testing/CMakeFiles/libInterpolate_CatchTests.dir/CatchTests/2D/Semantics.cpp.o
[ 73%] Building CXX object testing/CMakeFiles/libInterpolate_CatchTests.dir/CatchTests/2D/ThinPlateSplineInterpolatorTests.cpp.o
[ 76%] Building CXX object testing/CMakeFiles/libInterpolate_CatchTests.dir/CatchTests/2D/TriangleInterpolatorBaseTests.cpp.o
[ 80%] Building CXX object testing/CMakeFiles/libInterpolate_CatchTests.dir/CatchTests/Bugs/MonotonicInterpolatorWithFloat.cpp.o
[ 84%] Building CXX object testing/CMakeFiles/libInterpolate_CatchTests.dir/CatchTests/Devel.cpp.o
[ 88%] Building CXX object testing/CMakeFiles/libInterpolate_CatchTests.dir/CatchTests/Examples.cpp.o
[ 92%] Building CXX object testing/CMakeFiles/libInterpolate_CatchTests.dir/CatchTests/UtilsTests.cpp.o
/Users/dutsov_c/Documents/Year-2022/libInterpolate/testing/CatchTests/UtilsTests.cpp:287:38: error: 'iterator<std::forward_iterator_tag, double>' is deprecated [-Werror,-Wdeprecated-declarations]
struct StridedIterator : public std::iterator<std::forward_iterator_tag, T> {
                                     ^
/.../libInterpolate/testing/CatchTests/UtilsTests.cpp:409:27: note: in instantiation of template class 'StridedIterator<double>' requested here
  StridedIterator<double> begin(v.data(),2);
                          ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__iterator/iterator.h:27:29: note: 'iterator<std::forward_iterator_tag, double>' has been explicitly marked deprecated here
struct _LIBCPP_TEMPLATE_VIS _LIBCPP_DEPRECATED_IN_CXX17 iterator
                            ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__config:1066:39: note: expanded from macro '_LIBCPP_DEPRECATED_IN_CXX17'
#  define _LIBCPP_DEPRECATED_IN_CXX17 _LIBCPP_DEPRECATED
                                      ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__config:1043:48: note: expanded from macro '_LIBCPP_DEPRECATED'
#    define _LIBCPP_DEPRECATED __attribute__ ((deprecated))
                                               ^
1 error generated.
make[2]: *** [testing/CMakeFiles/libInterpolate_CatchTests.dir/CatchTests/UtilsTests.cpp.o] Error 1
make[1]: *** [testing/CMakeFiles/libInterpolate_CatchTests.dir/all] Error 2
make: *** [all] Error 2`

I rarely use OSX, but if needed I can provide you with more info

**Comment by CD3** [comment]
Thanks for the issue. It looks like the error is coming from a unit test file I was using to experiment with different index search methods. It is not being used by the library, so I will just delete it.

**Comment by CD3** [comment]
I removed the test code that triggered this error, but I don't have an OSX machine to test on. If you can, please test and let me know if it is fixed.
