### ISSUE TITLE
can set a scalar factor to zoom ?

### ISSUE THREAD

**Issue by Stephenfang51** [CD3/libInterpolate#13]
The function like "scipy.ndimage.interpolation.zoom" which implemented the spline interpolation
can just easily give a scale factor to zoom in or out the original array
How can I implement this with your excellent jobs ?

Thanks !

**Comment by CD3** [comment]
I am not familiar with that feature. Can you give a common use case? Does it increase the number of sample points over the same domain, or does it sample the same grid size over a smaller area of the function?

**Comment by Stephenfang51** [comment]
Yes, it's like if we got [1,2,3,4,5], and we want to zoom it to size 10 , it will zoom be like [1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5]
of course the interval value are now the same, it's just an example.

**Comment by CD3** [comment]
Ah, OK. For that I would write a helper function that takes a set of coordinates and returns the "scaled" set. Then you can pass those to an interpolator to fill the scaled array.

**Comment by Stephenfang51** [comment]
@CD3  Thanks for the suggestion
