### ISSUE TITLE
Add support for Windows and MacOS

### ISSUE THREAD

**Issue by CD3** [CD3/libInterpolate#14]
The library fails to compile on Windows and MacOS in conan-center's CI. Need to figure out why and fix.

https://github.com/conan-io/conan-center-index/pull/14939

**Comment by samuel-emrys** [comment]
To facilitate this, github actions provides free runners for macos, windows and linux. It could be worth utilising these to give you feedback on compatibility.

**Comment by CD3** [comment]
We now have GitHub workflows for testing on Windows and Mac OS. Thank you @uilianries .
