### ISSUE TITLE
It always turns out to be zero. the principle of use is unclear.

### ISSUE THREAD

**Issue by luzhskij** [CD3/libInterpolate#20]
Hello! First of all, thank you for the work done!

here is a code example:
```
	std::vector<double> lon;
	std::vector<double> lat;
	//0
	lat.push_back(-39.363024);
	lon.push_back(52.872388);
	//1
	lat.push_back(-37.615071); // maximum lat
	lon.push_back(119.453522);
	//2
	lat.push_back(-75.928);
	lon.push_back(119.754988);
	//3
	lat.push_back(-75.93703); // minimum lat
	lon.push_back(119.689077);
	//4
	lat.push_back(-69.968429);
	lon.push_back(76.1259);
	//5
	lat.push_back(-58.196226);
	lon.push_back(59.691912);
	//6
	lat.push_back(-44.978186);
	lon.push_back(53.709062);
	//7
	lat.push_back(-39.363024);
	lon.push_back(52.872388);

	_1D::CubicSplineInterpolator<double> interp;
	interp.setData(lat, lon);

	double minLat = -75.93703;
	double maxLat = -37.615071;

	std::vector<double> lon2;
	std::vector<double> lat2;

 // now I want to go from the minimum lat value to the maximum and generate new lon lat pairs
	for (auto m(minLat); m < maxLat; m+=0.5)	{
		double valLon = interp(m);
		if (valLon == 0) {
			std::cout << " 0 " << std::endl; // in every step :(			
		}
		else {
			lon2.push_back(valLon);
			lat2.push_back(m);
		}
	}
	std::cout << "new lat size: " << lat2.size() << " | new lon size: " << lon2.size() << std::endl;
```

I have a polygon that doesn't have many points and because of this it has sharp edges, I need to make it smoother.
But for some reason I always get 0 when interpolating.

**Comment by luzhskij** [comment]
in the picture the original polygon is shown in red, and in green what you want to get.

![Screenshot 2024-01-24 161105](https://github.com/CD3/libInterpolate/assets/7203449/c8184066-4dc2-46a8-a235-1d4425f137cb)

**Comment by CD3** [comment]
Hi, thanks for submitting the issue.

I have not dug into this yet, but I see a couple of issues.

First, this library only interpolates functions, i.e. y = f(x). To interpolate around the perimeter of a polygon, you would need to split the vertices into "high" and "low" . For example, at lat ~45 the bottom edit is at lon ~45, but the top edge is at long ~119. The library can't interpolate this type of data. You could get the green line by interpolating between the 6 vertices of the polygon excluding the top right corner.

Second, the interpolators assume that the input data is already sorted. So you need to sort the points by their lat before calling `setData(...)`. They also do not extrapolate at all. In fact, if a point ouside the interpolated range is passed in, the interpolators will return zero. So I think what is happening is that the first and last points in the data passed to `setData(...)` have an x value of -39.363024, so the interpolator thinks the range is -39.36024 to -39.36024 and returns zero for everything outside this range.

**Comment by luzhskij** [comment]
Hello! Thanks for the answer.
It looks like I need to think more carefully about the logic for handling my polygons.

**Comment by CD3** [comment]
You could create a parametric parameter that you use to then interpolate the x and y coordinates of the edges.

https://en.wikipedia.org/wiki/Parametric_equation

Start at one corner and keep track of the distance along the perimeter, then interpolate x and y with respect to the distance. Here is an example I got to work. I don't know if the shape it gives you is what you actually want.

```
  std::vector<double> x, y;  // x-y coordinates of corners
  x.push_back(-39.363024);
  y.push_back(52.872388);
  // 1
  x.push_back(-37.615071);
  y.push_back(119.453522);
  // 2
  x.push_back(-75.928);
  y.push_back(119.754988);
  // 3
  x.push_back(-75.93703);
  y.push_back(119.689077);
  // 4
  x.push_back(-69.968429);
  y.push_back(76.1259);
  // 5
  x.push_back(-58.196226);
  y.push_back(59.691912);
  // 6
  x.push_back(-44.978186);
  y.push_back(53.709062);
  // 7
  x.push_back(-39.363024);
  y.push_back(52.872388);

  // now create a parametric variable that we can use to interpolate
  std::vector<double> t;

  t.push_back(0);
  auto distance = [](double x1, double y1, double x2, double y2) { return sqrt(pow(x2 - x1, 2) + pow(y2 - y1, 2)); };
  for(size_t i = 1; i < x.size(); ++i) {
    t.push_back(t[i - 1] + distance(x[i - 1], y[i - 1], x[i], y[i]));
  }

  _1D::CubicSplineInterpolator<double> interp_x, interp_y;
  interp_x.setData(t, x);
  interp_y.setData(t, y);

  {
    std::ofstream out("polygon-raw.txt");
    for(size_t i = 0; i < x.size(); ++i) {
      out << x[i] << " " << y[i] << "\n";
    }
  }

  {
    std::ofstream out("polygon-interpolated.txt");
    int           N  = 100;
    double        dt = t[t.size() - 1] / (N - 1);
    for(int i = 0; i < N; ++i) {
      out << interp_x(dt * i) << " " << interp_y(dt * i) << "\n";
    }
  }

```

That code gives an image that looks like this, which no longer looks like a polygon...
![image](https://github.com/CD3/libInterpolate/assets/693953/b74c3cc0-e8c7-4665-96e6-56f2eb6fab3d)
