### ISSUE TITLE
Removes all trailing spaces ?

### ISSUE THREAD

**Issue by Gjacquenot** [CD3/libInterpolate#21]
Thanks for this library!

Code contains multiple trailing spaces. This means that an edition with an IDE configured to remove trailing spaces modifies lot of files...

Are you interested in a pull request that removes all trailing spaces ?

**Comment by CD3** [comment]
Hi, sorry for the delay. Yes, I would. This library was started before I got an automated code formatting setup in vim/neovim.

**Comment by tao13146500073** [comment]
the 2d nearest interpolation seems not work
