### ISSUE TITLE
MacOS status support

### ISSUE THREAD

**Issue by uilianries** [CD3/libInterpolate#23]
Hello, we received an issue in ConanCenterIndex about confirming libinterpolate is building in Mac:

https://github.com/conan-io/conan-center-index/issues/24571#issuecomment-2220009629

Not sure what's the current status, so I would like to ask if MacOS is now supported. Thanks! 

Related to #14

/cc @thomas-harries-hasselbalch-maersk

**Comment by CD3** [comment]
Hi, thanks for reaching out. The only reason Mac is not listed as supported is that I don't use Mac and don't have a machine to test on. I know I could setup CI to run tests on other platforms, but the feedback loop is pretty long and cumbersome compared to a local machine.

I don't expect there to be any reason it would not build on Mac, so if someone else has done that, I would say it supports Mac OS.

**Comment by CD3** [comment]
Hi, thanks for reaching out. The only reason Mac is not listed as supported is that I don't use Mac and don't have a machine to test on. I know I could setup CI to run tests on other platforms, but the feedback loop is pretty long and cumbersome compared to a local machine.

I don't expect there to be any reason it would not build on Mac, so if someone else has done that, I would say it supports Mac OS.

**Comment by CD3** [comment]
CI now tests on Mac OS.
