### ISSUE TITLE
Bilinear interpolation doesn't work.

### ISSUE THREAD

**Issue by realArtichoke** [CD3/libInterpolate#3]
I am trying to use bilinear interpolation for inpainting a part of an image.
```vector<double> xtrain, ytrain, xinter, yinter;
	vector<double> ztrain;
	for (int i = 0; i < img.rows; i++) {
		for (int j = 0; j < img.cols; j++) {
			if (img.at<Vec3b>(i, j)[channel] != 0) {
				xtrain.push_back(j);
				ytrain.push_back(i);
				ztrain.push_back(img.at<Vec3b>(i, j)[channel]);
			}
			else {
				xinter.push_back(j);
				yinter.push_back(i);
			}
		}
	}
	_2D::BilinearInterpolator<double> interp = 
		_2D::BilinearInterpolator<double>(xtrain.size(), xtrain.data(), ytrain.data(), ztrain.data());
	vector<double> zans;
	for (int i = 0; i < xinter.size(); i++) {
		double res = interp(xinter[i], yinter[i]);
		img.at<Vec3b>(yinter[i], xinter[i])[channel] = res;
	}
```

It doesn't do anything. Debugger showed me it happens because `y` is outside of the `Y`s boundaries in `BilinearInterpolator<Real>::operator()( Real x, Real y )`. And these boundaries are between 0 and 0(`(*Y)(0) ` and `(*Y)(Y->size()-1)` )

`xData`, `yData`, `zData` are the same size and correct.

How to fix it?

**Comment by CD3** [comment]
Thanks for using the library and submitting an issue.

So it looks like you are scanning an image and filling in dropped pixels by interpolating the image. Correct?

For the bilinear interpolator, data must be on a regular grid, and then you can interpolate to points between grid lines. In your case, points on the grid are missing, so the data is not on a regular grid. Also, the function that detects the grid lines is pretty simple, and it expect the y coordinates to vary first (like gnuplot). So, the input data should look like

x  y  z

1 1 3
1 2 4
1 3 2
2 1 4
2 2 4
2 3 2

The function looks for the index where x changes and assumes that that is the size of the y-dimension. Here it would detect that Ny = 3.

In your example, the x data is varying first
x  y  z

1 1 3
2 1 4
1 2 2
2 2 4
1 3 4
2 3 2

Here it detects that Ny = 1, so its just one coordinate. The interpolator is not able to determine the range correctly.

You have a couple of options.

1) There is a `_2D::ThinPlateSplineInterpolator<Real>` that does not require the data to be on a regular grid. However, this method does a matrix inversion based on the entire data set, so it is going to be slow. You should make sure you compile in release mode. I don't know how big your images are, but its possible they will be too big.

2) Use a 1D interpolator on each row and/or column. You could interpolate the missing pixels using both the row and column that the pixel belongs to and then average them.

**Comment by realArtichoke** [comment]
Thank you for quick reply! That helped very much.  

1d Linear interpolation works fine. I expected Bilinear would work like SciPy interp2d. Sad to hear it doesn't.

'_2D::ThinPlateSplineInterpolator<Real>' causes bad_alloc because image is too big for it.

**Comment by CD3** [comment]
I will look into SciPy's implementation. I basically just haven't had a need for it, but I can see how it would be very useful.

**Comment by dsienkiewicz-lab4motion** [comment]
@CD3 Did you do this ?

**Comment by CD3** [comment]
@dsienkiewicz-lab4motion No. The bilinear interpolator requires a regular grid. It would need to be implemented as a separate class that handles missing grid points/irregular grids, and I haven't needed it for anything yet.
