### ISSUE TITLE
Getting errors on MSVC C++20

### ISSUE THREAD

**Issue by suhasghorp** [CD3/libInterpolate#8]
Hello,

Trying to use libInterpolate with msvc c++20 standard on Windows and getting tons of erros like these. Am I doing anything wrong?
Is the library supposed to work on windows/msvc ?
Thanks

>------ Build All started: Project: FinEngLech, Configuration: x64-Debug ------
  [1/3] Building CXX object CMakeFiles\YieldCurveTest.dir\src\YieldCurve.cpp.obj
  FAILED: CMakeFiles/YieldCurveTest.dir/src/YieldCurve.cpp.obj 
  "C:\PROGRA~1\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.30.30705\bin\Hostx64\x64\cl.exe"  /nologo /TP -DFMT_LOCALE -DFMT_SHARED -IC:\Users\suhasghorp\source\repos\FinEngLech\extern -IC:\Users\suhasghorp\source\repos\FinEngLech\include -IC:\vcpkg\installed\x64-windows\include -IC:\eigen-3.4.0 /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MDd /Zi /Ob0 /Od /RTC1 /std:c++latest -std:c++20 /showIncludes /FoCMakeFiles\YieldCurveTest.dir\src\YieldCurve.cpp.obj /FdCMakeFiles\YieldCurveTest.dir\ /FS -c C:\Users\suhasghorp\source\repos\FinEngLech\src\YieldCurve.cpp
C:\Users\suhasghorp\source\repos\FinEngLech\out\build\x64-Debug\cl : Command line warning D9025: overriding '/std:c++latest' with '/std:c++20'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_1D\InterpolatorBase.hpp(223): warning C4068: unknown pragma 'parallel'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_1D\CubicSplineInterpolator.hpp(146): error C2589: '(': illegal token on right side of '::'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_1D\CubicSplineInterpolator.hpp(146): error C3878: syntax error: unexpected token '(' following 'expression'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_1D/CubicSplineInterpolator.hpp(146): note: error recovery skipped: '( ( identifier'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_1D\CubicSplineInterpolator.hpp(146): error C2760: syntax error: ')' was unexpected here; expected ';'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_1D\CubicSplineInterpolator.hpp(146): error C3878: syntax error: unexpected token ')' following 'expression_statement'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_1D/CubicSplineInterpolator.hpp(146): note: error recovery skipped: ') >'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_1D/CubicSplineInterpolator.hpp(146): note: error recovery skipped: ') ?'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_1D\CubicSplineInterpolator.hpp(146): error C2760: syntax error: ':' was unexpected here; expected ';'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_1D\CubicSplineInterpolator.hpp(146): error C3878: syntax error: unexpected token ':' following 'expression_statement'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_1D/CubicSplineInterpolator.hpp(146): note: error recovery skipped: ':'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_1D/CubicSplineInterpolator.hpp(146): note: error recovery skipped: ')'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_1D\CubicSplineInterpolator.hpp(147): error C2589: '(': illegal token on right side of '::'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_1D\CubicSplineInterpolator.hpp(147): error C3878: syntax error: unexpected token '(' following 'expression'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_1D/CubicSplineInterpolator.hpp(147): note: error recovery skipped: '( ( identifier'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_1D\CubicSplineInterpolator.hpp(147): error C2760: syntax error: ')' was unexpected here; expected ';'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_1D\CubicSplineInterpolator.hpp(147): error C3878: syntax error: unexpected token ')' following 'expression_statement'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_1D/CubicSplineInterpolator.hpp(147): note: error recovery skipped: ') <'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_1D/CubicSplineInterpolator.hpp(147): note: error recovery skipped: ') ?'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_1D\CubicSplineInterpolator.hpp(147): error C2760: syntax error: ':' was unexpected here; expected ';'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_1D\CubicSplineInterpolator.hpp(147): error C3878: syntax error: unexpected token ':' following 'expression_statement'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_1D/CubicSplineInterpolator.hpp(147): note: error recovery skipped: ':'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_1D/CubicSplineInterpolator.hpp(147): note: error recovery skipped: ')'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(149): error C2589: '(': illegal token on right side of '::'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(149): error C3878: syntax error: unexpected token '(' following 'expression'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(149): note: error recovery skipped: '( ( identifier  . . . constant'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(149): error C2760: syntax error: ')' was unexpected here; expected ';'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(149): error C3878: syntax error: unexpected token ')' following 'expression_statement'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(149): note: error recovery skipped: ') >'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(149): note: error recovery skipped: ') ?'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(149): error C2760: syntax error: ':' was unexpected here; expected ';'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(149): error C3878: syntax error: unexpected token ':' following 'expression_statement'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(149): note: error recovery skipped: ':'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(149): note: error recovery skipped: ')'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(150): error C2589: '(': illegal token on right side of '::'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(150): error C3878: syntax error: unexpected token '(' following 'expression'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(150): note: error recovery skipped: '( ( identifier  . . . constant'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(150): error C2760: syntax error: ')' was unexpected here; expected ';'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(150): error C3878: syntax error: unexpected token ')' following 'expression_statement'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(150): note: error recovery skipped: ') <'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(150): note: error recovery skipped: ') ?'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(150): error C2760: syntax error: ':' was unexpected here; expected ';'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(150): error C3878: syntax error: unexpected token ':' following 'expression_statement'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(150): note: error recovery skipped: ':'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(150): note: error recovery skipped: ')'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(163): error C2589: '(': illegal token on right side of '::'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(163): error C3878: syntax error: unexpected token '(' following 'expression'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(163): note: error recovery skipped: '( ( identifier'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(163): error C2760: syntax error: ')' was unexpected here; expected ';'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(163): error C3878: syntax error: unexpected token ')' following 'expression_statement'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(163): note: error recovery skipped: ') >'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(163): note: error recovery skipped: ') ?'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(163): error C2760: syntax error: ':' was unexpected here; expected ';'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(163): error C3878: syntax error: unexpected token ':' following 'expression_statement'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(163): note: error recovery skipped: ':'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(163): note: error recovery skipped: ')'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(164): error C2589: '(': illegal token on right side of '::'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(164): error C3878: syntax error: unexpected token '(' following 'expression'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(164): note: error recovery skipped: '( ( identifier  . . . constant'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(164): error C2760: syntax error: ')' was unexpected here; expected ';'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(164): error C3878: syntax error: unexpected token ')' following 'expression_statement'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(164): note: error recovery skipped: ') <'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(164): note: error recovery skipped: ') ?'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(164): error C2760: syntax error: ':' was unexpected here; expected ';'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(164): error C3878: syntax error: unexpected token ':' following 'expression_statement'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(164): note: error recovery skipped: ':'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(164): note: error recovery skipped: ')'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(179): error C2589: '(': illegal token on right side of '::'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(179): error C3878: syntax error: unexpected token '(' following 'expression'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(179): note: error recovery skipped: '( ( identifier  . . . constant'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(179): error C2760: syntax error: ')' was unexpected here; expected ';'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(179): error C3878: syntax error: unexpected token ')' following 'expression_statement'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(179): note: error recovery skipped: ') >'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(179): note: error recovery skipped: ') ?'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(179): error C2760: syntax error: ':' was unexpected here; expected ';'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(179): error C3878: syntax error: unexpected token ':' following 'expression_statement'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(179): note: error recovery skipped: ':'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(179): note: error recovery skipped: ')'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(180): error C2589: '(': illegal token on right side of '::'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(180): error C3878: syntax error: unexpected token '(' following 'expression'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(180): note: error recovery skipped: '( ( identifier  . . . constant'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(180): error C2760: syntax error: ')' was unexpected here; expected ';'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(180): error C3878: syntax error: unexpected token ')' following 'expression_statement'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(180): note: error recovery skipped: ') <'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(180): note: error recovery skipped: ') ?'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(180): error C2760: syntax error: ':' was unexpected here; expected ';'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(180): error C3878: syntax error: unexpected token ':' following 'expression_statement'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(180): note: error recovery skipped: ':'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(180): note: error recovery skipped: ')'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(193): error C2589: '(': illegal token on right side of '::'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(193): error C3878: syntax error: unexpected token '(' following 'expression'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(193): note: error recovery skipped: '( ( identifier'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(193): error C2760: syntax error: ')' was unexpected here; expected ';'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(193): error C3878: syntax error: unexpected token ')' following 'expression_statement'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(193): note: error recovery skipped: ') >'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(193): note: error recovery skipped: ') ?'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(193): error C2760: syntax error: ':' was unexpected here; expected ';'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(193): error C3878: syntax error: unexpected token ':' following 'expression_statement'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(193): note: error recovery skipped: ':'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(193): note: error recovery skipped: ')'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(194): error C2589: '(': illegal token on right side of '::'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(194): error C3878: syntax error: unexpected token '(' following 'expression'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(194): note: error recovery skipped: '( ( identifier  . . . constant'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(194): error C2760: syntax error: ')' was unexpected here; expected ';'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(194): error C3878: syntax error: unexpected token ')' following 'expression_statement'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(194): note: error recovery skipped: ') <'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(194): note: error recovery skipped: ') ?'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(194): error C2760: syntax error: ':' was unexpected here; expected ';'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(194): error C3878: syntax error: unexpected token ':' following 'expression_statement'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(194): note: error recovery skipped: ':'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(194): note: error recovery skipped: ')'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(208): error C2589: '(': illegal token on right side of '::'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(208): error C3878: syntax error: unexpected token '(' following 'expression'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(208): note: error recovery skipped: '( ( identifier  . . . constant'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(208): error C2760: syntax error: ')' was unexpected here; expected ';'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(208): error C3878: syntax error: unexpected token ')' following 'expression_statement'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(208): note: error recovery skipped: ') >'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(208): note: error recovery skipped: ') ?'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(208): error C2760: syntax error: ':' was unexpected here; expected ';'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(208): error C3878: syntax error: unexpected token ':' following 'expression_statement'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(208): note: error recovery skipped: ':'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(208): note: error recovery skipped: ')'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(209): error C2589: '(': illegal token on right side of '::'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(209): error C3878: syntax error: unexpected token '(' following 'expression'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(209): note: error recovery skipped: '( ( identifier  . . . constant'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(209): error C2760: syntax error: ')' was unexpected here; expected ';'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(209): error C3878: syntax error: unexpected token ')' following 'expression_statement'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(209): note: error recovery skipped: ') <'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(209): note: error recovery skipped: ') ?'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(209): error C2760: syntax error: ':' was unexpected here; expected ';'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(209): error C3878: syntax error: unexpected token ':' following 'expression_statement'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(209): note: error recovery skipped: ':'
  C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\./Interpolators/_2D/BicubicInterpolator.hpp(209): note: error recovery skipped: ')'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(210): error C2589: '(': illegal token on right side of '::'
C:\Users\suhasghorp\source\repos\FinEngLech\extern\libInterpolate\Interpolators\_2D\BicubicInterpolator.hpp(210): error C3878: syntax error: unexpected token '(' following 'expression'

**Comment by CD3** [comment]
Are you trying to compile your code or are these errors from building the unit tests?

**Comment by suhasghorp** [comment]
Trying to compile. Figured it was because of Windows.h header being pulled indirectly somewhere in the library which defines its own min and max macros. The solution is to wrap calls to std::max in a parenthesis like (std::max) so, same for std::min 
This needs to be done all over the codebase. Thanks
